job: extension
config:
  name: my-lora
  process:
  - type: sd_trainer
    training_folder: output
    device: cuda:0
    network:
      type: lora
      linear: 16
      linear_alpha: 16
    save:
      dtype: float16
      save_every: 500
      max_step_saves_to_keep: 4
      push_to_hub: true
      hf_repo_id: firofame/my-lora
      hf_private: true
    datasets:
    - folder_path: /root/images
      caption_ext: txt
      caption_dropout_rate: 0
      shuffle_tokens: false
      cache_latents_to_disk: true
      resolution: [ 512, 768 ]
    train:
      batch_size: 1
      steps: 600
      gradient_accumulation_steps: 1
      train_unet: true
      train_text_encoder: false
      gradient_checkpointing: true
      noise_scheduler: flowmatch
      optimizer: adamw
      lr: 1e-4
      dtype: bf16
      skip_first_sample: true
      disable_sampling: true
    model:
      name_or_path: black-forest-labs/FLUX.1-dev
      is_flux: true
      quantize: false
      low_vram: false
    sample:
      sampler: flowmatch
      sample_every: 1000
      width: 512
      height: 768
      prompts:
      - A person in a bustling cafe firofame
      neg: ''
      seed: 42
      walk_seed: true
      guidance_scale: 3
      sample_steps: 20
    trigger_word: firofame
meta:
  name: "[name]"
  version: '1.0'
