job: extension
config:
  name: my-lora
  process:
  - type: sd_trainer
    training_folder: output
    device: cuda:0
    network:
      type: lora
      linear: 16
      linear_alpha: 16
    save:
      dtype: float16
      save_every: 250
      max_step_saves_to_keep: 4
      push_to_hub: true
      hf_repo_id: firofame/my-lora
      hf_private: true
    datasets:
    - folder_path: /root/images
      caption_ext: txt
      caption_dropout_rate: 0
      shuffle_tokens: false
      cache_latents_to_disk: true
      resolution:
      - 512
      - 768
    train:
      batch_size: 1
      steps: 1000
      gradient_accumulation_steps: 1
      train_unet: true
      train_text_encoder: false
      gradient_checkpointing: true
      noise_scheduler: flowmatch
      optimizer: adamw8bit
      lr: 0.0004
      ema_config:
        use_ema: true
        ema_decay: 0.99
      dtype: bf16
      skip_first_sample: true
      disable_sampling: true
    model:
      name_or_path: black-forest-labs/FLUX.1-dev
      is_flux: true
      quantize: false
      low_vram: false
    sample:
      sampler: flowmatch
      sample_every: 1000
      width: 1024
      height: 1024
      prompts:
      - A person in a bustling cafe firofame
      neg: ''
      seed: 42
      walk_seed: true
      guidance_scale: 4
      sample_steps: 28
    trigger_word: firofame
meta:
  name: my-lora
  version: '1.0'
