[general]
flip_aug = true
color_aug = false

[[datasets]]
enable_bucket = true
resolution = [512,768]
bucket_reso_steps = 64
max_bucket_reso = 2048
min_bucket_reso = 128
bucket_no_upscale = false
batch_size = 1
random_crop = false
shuffle_caption = false

  [[datasets.subsets]]
  image_dir = "/root/images"
  num_repeats = 100
  caption_extension = ".txt"